### ISSUE TITLE
min.dt likely not working as intended

### ISSUE THREAD

**Issue by frousseu** [ianjonsen/aniMotum#38] opened 2022-12-30 08:52 UTC
Hello!

The `min.dt` argument does not seem to work as intended, at least not the way I expected it to work. Instead of keeping all observations that will be at least separated by the specified time gap, it seems to filter out all locations having neighbouring locations with the specified time gap. This discards whole blocks of consecutive observations where several could be retained if only some observations were discarded. Perhaps the filtering is done on the result of a `diff`? Here is an example of what is kept win a `min.dt = 72` hours. Only the ones with `diff >= min.dt` are kept, but several more could have been kept.

```r
library(aniMotum)

step<-as.difftime(72,units="hours")

fit <- fit_ssm(ellie, 
               vmax = Inf, 
               ang=c(180,180),
               distlim = c(Inf, Inf),
               min.dt=as.numeric(step,units="secs"), 
               model = "crw", 
               time.step = 24, 
               control = ssm_control(verbose = 0)
              ) 

res<-grab(fit,"fitted")
nrow(res)
## [1] 6

m<-match(res$date,ellie$date)

c(NA,diff(ellie$date))
##  [1]       NA  23.76139  23.46556  16.99889  31.07861  19.71444  23.75889  27.15667  34.18917  23.91389  33.04583  47.29444
##  [13]  37.40750  26.82000  28.38111  26.45139  24.20083  22.06111  35.18556  25.62111  35.27667  28.55083  35.88028  30.36000
##  [25]  46.05861  27.46583  38.02083  33.67778  28.73806  41.37528  31.91194  41.69694  45.99000  46.97639  51.59778  41.30556
##  [37]  26.26028  25.50528  39.25556  52.79083  34.16806  42.31444  49.82639  28.74806  58.45861  51.70111  28.90222  50.58556
##  [49]  67.34806  42.93167  25.25472  52.13417  59.22444  58.19111  60.65667  69.71639  53.87000  60.23778  61.93556  77.85444
##  [61]  84.40944 116.21694  85.85556  84.90222

c(NA,diff(ellie$date))[m]
## [1]        NA  77.85444  84.40944 116.21694  85.85556  84.90222

res$date
## [1] "2012-03-05 05:09:33 UTC" "2012-06-09 14:25:11 UTC" "2012-06-13 02:49:45 UTC" "2012-06-17 23:02:46 UTC" "2012-06-## 21 12:54:06 UTC"
## [6] "2012-06-25 01:48:14 UTC"

ellie$date[m]
## [1] "2012-03-05 05:09:33 UTC" "2012-06-09 14:25:11 UTC" "2012-06-13 02:49:45 UTC" "2012-06-17 23:02:46 UTC" "2012-06-## 21 12:54:06 UTC"
## [6] "2012-06-25 01:48:14 UTC"
```

I haven't thought yet of an efficient way to keep all observations that will respect the `min.dt` threshold.

Happy holidays!
François

**Comment by ianjonsen** [comment] 2023-01-06 14:56
Yes, you're right this is not really what was originally intended but the problem is computational efficiency. I will find a solution for the next update, but if you have any subsequent ideas then please post them here. Thanks

**Comment by frousseu** [comment] 2023-01-06 15:20
As an excuse for trying ChatGPT, I actually submitted the problem to it this morning and it found a really inefficient solution using two imbricated for loops (still, I was completely amazed!). I asked for a more efficient solution using cumsum and difftime, but it wasn't working properly. For now, the only thing I can think of is using a while that randomly deletes observations based on a diff until the time gap is reached. Ideally, one would optimize this to minimize the largest gap between two consecutive observations, but I'm not sure how to do that. One could also optimize for keeping the maximum number of observations. I'm not sure whether these two objectives can have different solutions. Indeed, the problem is a bit trickier than what I initially thought. If I find something I will let you know.

**Comment by ianjonsen** [comment] 2023-06-13 13:34
I will have time to work on this issue in 1-2 weeks. In the meantime, you will have to filter your data prior to passing to `fit_ssm`. In your case, a simplistic solution would be to pass every 2nd observation to `fit_ssm`.

**Comment by frousseu** [comment] 2023-06-13 13:48
A few weeks (months?) ago I actually coded a decent solution for filtering according to a threshold, but I just need to make the code a bit more robust and clean to submit a pull request. It uses a while that removes observations until the threshold is met and it tries to minimize the maximum gap between observations. It is not the fastest solution, but it is quick enough and it is probably sufficient for any realistic dataset. I could work on this in the coming weeks if needed.

**Comment by MonaFuhrmann** [comment] 2023-06-13 14:01
Thanks so much Ian and Francoirs! Yes it would help me a lot. 
Actually we are using the package here in Norway at the marine institute, not only for animal movements, but movements of underwater vehicles (such as ROVs). I can send a dataset (with data for every second), if you want to try a real dataset;)
In general we would like the model to smooth out high data density areas (where the vehicle stops).

**Comment by ianjonsen** [comment] 2023-06-13 14:11
@frousseu submit the pull request when you're ready but I can worry about cleaning it up and I will need to test/tweak for computational efficiency before I'll merge it into the master branch. @MonaFuhrmann if you can share the data here then we can both use it for testing - thanks.

**Comment by MonaFuhrmann** [comment] 2023-06-13 15:18
[ROV_24.txt](https://github.com/ianjonsen/aniMotum/files/11736451/ROV_24.txt)
This is an example track (time = UTC, lat/lon in decimals )

**Comment by ianjonsen** [comment] 2023-10-31 18:43
Hi @MonaFuhrmann, thanks for the code and additional test data. I've pushed an update to the `dev` branch that should solve your problem. You can install the dev branch via:

`remotes::install_github("ianjonsen/aniMotum@dev", dependencies = TRUE)`

In this update the `min.dt` argument is set to 0 by default - only subsequent observations occurring at the same time get filtered out. It shouldn't be necessary to change from the default `min.dt` in most cases. I've also changed some of the data prep code where prediction times that exactly match observation times were adjusted by 1 s. This failed with your data because the observations are at 1 s intervals - so all prediction and observation times matched exactly and this caused the model fit errors. The code now adjusts prediction times by 0.5 s. The following now runs without error:

```
require(tidyverse)
require(aniMotum)

d <- read_csv("ROV_24.txt") %>%
  mutate(date = lubridate::ymd_hms(paste(date, time), tz = "UTC")) %>%
  mutate(id = 1) %>%
  mutate(lc = "G") %>%
  select(id, date, lc, lon, lat)

## turn off estimation of rho_o (observation error correlation term)
fit <- fit_ssm(d, model = "crw", time.step = 10/3600, map = list(rho_o = factor(NA)))

plot(fit, "p")
```

**Comment by ianjonsen** [comment] 2023-11-01 16:05
Closing this issue - following the above change to the default `min.dt` argument, and as `min.dt > 0` should not generally be necessary.

**Closed by ianjonsen** 2023-11-01 16:05 UTC

**Comment by ianjonsen** [comment] 2023-11-02 09:34
The above fixes are now available in the staging branch, which is more stable than dev. Install via:

`remotes::install_github("ianjonsen/aniMotum@staging", dependencies = TRUE)`
